name: Accessibility Scanner

on:
  workflow_dispatch:

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: github/accessibility-scanner@v2
        with:
          urls: |
            https://alliethu.github.io
            https://alliethu.github.io/about
            https://alliethu.github.io/connect
            https://alliethu.github.io/tinkering
          repository: alliethu/alliethu.github.io
          token: ${{ secrets.GH_TOKEN }}
          cache_key: cached_results-alliethu.github.io.json
